In [2]:
import pandas as pd 
import plotly.express as px

In [ ]:
DeepCoNN	Amazon Music	0,4388	0,6624	0,4427
D-ATTN	Amazon Music	0.4506	0.6713	0.4743
MPCN	Amazon Music	0,9405	0,9698	0,7496
NARRE	Amazon Music	0.5577	0.7468	0.4564
DAML	Amazon Music	0.8842	0.9403	0.7517
CARL	Amazon Music	0.4270	0,6530	0.5160
CARP	Amazon Music	0.4390	0,6620	0.5390
PARL	Amazon Music	0,7190	0,8470	0,8525

In [3]:
algorithms = ["DeepCoNN", "D-ATTN", "MPCN", "NARRE", "DAML", "CARL", "CARP", "PARL"]
dataset = ["Amazon_Music"]*8
mse = [0.4388, 0.4506, 0.9405, 0.5577, 0.8842, 0.4270, 0.4390, 0.7190]
rmse = [0.6624, 0.6713, 0.9698, 0.7468, 0.9403, 0.6530, 0.6620, 0.8470]
mae = [0.4427, 0.4743, 0.7496, 0.4564, 0.7517, 0.5160, 0.5390, 0.8525]

In [4]:
data = pd.DataFrame({"Algorithm":algorithms, "Dataset":dataset, "mse":mse, "rmse":rmse, "mae":mae})
data.head()

  Algorithm       Dataset     mse    rmse     mae
0  DeepCoNN  Amazon_Music  0.4388  0.6624  0.4427
1    D-ATTN  Amazon_Music  0.4506  0.6713  0.4743
2      MPCN  Amazon_Music  0.9405  0.9698  0.7496
3     NARRE  Amazon_Music  0.5577  0.7468  0.4564
4      DAML  Amazon_Music  0.8842  0.9403  0.7517

In [8]:
data.apply(lambda row: print(type(row)))

0    DeepCoNN
1      D-ATTN
2        MPCN
3       NARRE
4        DAML
5        CARL
6        CARP
7        PARL
Name: Algorithm, dtype: object
0    Amazon_Music
1    Amazon_Music
2    Amazon_Music
3    Amazon_Music
4    Amazon_Music
5    Amazon_Music
6    Amazon_Music
7    Amazon_Music
Name: Dataset, dtype: object
0    0.4388
1    0.4506
2    0.9405
3    0.5577
4    0.8842
5    0.4270
6    0.4390
7    0.7190
Name: mse, dtype: float64
0    0.6624
1    0.6713
2    0.9698
3    0.7468
4    0.9403
5    0.6530
6    0.6620
7    0.8470
Name: rmse, dtype: float64
0    0.4427
1    0.4743
2    0.7496
3    0.4564
4    0.7517
5    0.5160
6    0.5390
7    0.8525
Name: mae, dtype: float64

Algorithm    None
Dataset      None
mse          None
rmse         None
mae          None
dtype: object

In [14]:
df = pd.read_csv("Experimental_setup_1.csv")
df.head()

,Algorithm,Dataset,Precision@10,Recall@10,F1@10,Precision@20,Recall@20,F1@20,RMSE
0,PMF,Amazon,"0,123","0,1011","0,111","0,0924","0,1269","0,1069","1,1204"
1,PMF,Yelp,"0,1056","0,0779","0,0897","0,0858","0,0958","0,0905","1,2481"
2,ConvMF,Amazon,"0,1294","0,1064","0,1168","0,0973","0,1335","0,1125","1,0425"
3,ConvMF,Yelp,"0,1111","0,082","0,0944","0,0903","0,1008","0,0953","1,187"
4,DeepCoNN CNN,Amazon,"0,1368","0,1124","0,1234","0,1028","0,1411","0,1189","1,1451"

In [15]:
def str_to_float(col):
    df[col] = df[col].map(lambda x: float(x.replace(',', '.')))
    
columns = df.columns[2:]
for col in columns: str_to_float(col)

In [16]:
df.head()

,Algorithm,Dataset,Precision@10,Recall@10,F1@10,Precision@20,Recall@20,F1@20,RMSE
0,PMF,Amazon,0.1230,0.1011,0.1110,0.0924,0.1269,0.1069,1.1204
1,PMF,Yelp,0.1056,0.0779,0.0897,0.0858,0.0958,0.0905,1.2481
2,ConvMF,Amazon,0.1294,0.1064,0.1168,0.0973,0.1335,0.1125,1.0425
3,ConvMF,Yelp,0.1111,0.0820,0.0944,0.0903,0.1008,0.0953,1.1870
4,DeepCoNN CNN,Amazon,0.1368,0.1124,0.1234,0.1028,0.1411,0.1189,1.1451

In [11]:
data.to_csv("Experimental_setup.csv", index=False)

In [10]:
df = df.loc[df['Dataset'] == "Amazon"]

In [11]:
px.bar(df, x = 'Algorithm', y = 'Precision@10')